#!/usr/bin/env python3
"""把仓库里的 Obsidian 笔记同步成 docs/ 下的 Hugo 站点内容。

职责边界：
  - 笔记（model_arch/、infra/ …）永远是唯一的内容真相来源，本工具**不修改笔记**。
  - 本站点是唯一的内容清单，决定「发布什么、每篇的元信息是什么」。
  - 生成物（docs/content/**）不入库，由本地或 CI 每次运行本脚本产出。

用法：
    python3 tools/sync.py              # 生成 docs/content/
    python3 tools/sync.py --check      # 只校验并比对，不写文件（CI 第一步用）
    python3 tools/sync.py --strict     # 把 warning 也当成失败
    python3 tools/sync.py --clean      # 先清空 docs/content 再生成
    python3 tools/sync.py --serve      # 生成后启动 hugo server 本地预览
"""

from __future__ import annotations

import argparse
import datetime as _dt
import json
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
MANIFEST_PATH = REPO / "tools" / "status.json"
DOCS = REPO / "docs"
CONTENT = DOCS / "content"
PIN_CSS = DOCS / "assets" / "css" / "extended" / "pin-cards.css"

GEN_MARK = "<!-- generated by tools/sync.py"
SLUG_RE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")
# 开围栏：最多 3 个前导空格 + 3 个以上 ` 或 ~
FENCE_OPEN_RE = re.compile(r"^ {0,3}(`{3,}|~{3,})")
PIN_RULE_RE = re.compile(r"^\.post-entry\.pin-([A-Za-z0-9_-]+)", re.M)
# 行内 markdown 链接，指向 .md（排除图片、外链、纯锚点）
MD_LINK_RE = re.compile(r"(?<!!)\[([^\]\n]*)\]\((?!https?:|mailto:|#)([^)\n]+?\.md)(#[^)\n]*)?\)")
EMBED_RE = re.compile(r"!\[\[([^\]\n]+?)\]\]")
WIKILINK_RE = re.compile(r"(?<!!)\[\[([^\]\n]+?)\]\]")
HIGHLIGHT_RE = re.compile(r"==(?=\S)([^\n=]+?)(?<=\S)==")
H1_RE = re.compile(r"^#\s+")


class Report:
    """收集错误与警告。错误会让进程退出码非 0，警告默认只是提示。"""

    def __init__(self) -> None:
        self.errors: list[str] = []
        self.warnings: list[str] = []
        self.notes: list[str] = []

    def error(self, msg: str) -> None:
        self.errors.append(msg)

    def warn(self, msg: str) -> None:
        self.warnings.append(msg)

    def note(self, msg: str) -> None:
        self.notes.append(msg)


# --------------------------------------------------------------------------
# 清单加载与校验
# --------------------------------------------------------------------------

def load_manifest(report: Report) -> dict:
    if not MANIFEST_PATH.exists():
        report.error(f"找不到清单文件: {MANIFEST_PATH.relative_to(REPO)}")
        return {}
    try:
        raw = MANIFEST_PATH.read_text(encoding="utf-8")
    except OSError as exc:
        report.error(f"读取清单失败: {exc}")
        return {}
    try:
        data = json.loads(raw)
    except json.JSONDecodeError as exc:
        report.error(f"status.json 不是合法 JSON: {exc}")
        return {}
    if data.get("schemaVersion") != 1:
        report.error(f"status.json 的 schemaVersion 必须是 1，当前是 {data.get('schemaVersion')!r}")
    return data


def known_pins() -> set:
    """从 pin-cards.css 里读出所有已定义配色的 pin 名字。"""
    if not PIN_CSS.exists():
        return set()
    return set(PIN_RULE_RE.findall(PIN_CSS.read_text(encoding="utf-8")))


def validate_manifest(manifest: dict, report: Report) -> None:
    pins = known_pins()
    if not pins:
        report.warn(f"没有从 {PIN_CSS.relative_to(REPO)} 读到任何 pin 配色规则，pin 校验已跳过")

    site = manifest.get("site") or {}
    for key in ("title", "baseURL"):
        if not site.get(key):
            report.error(f"site.{key} 缺失")

    # 同时校验 hugo.yaml 与清单一致，避免两份配置各说各话
    hugo_yaml = DOCS / "hugo.yaml"
    if hugo_yaml.exists() and site.get("baseURL"):
        text = hugo_yaml.read_text(encoding="utf-8")
        m = re.search(r'^baseURL:\s*"?([^"\n]+)"?\s*$', text, re.M)
        if m and m.group(1).strip().rstrip("/") != site["baseURL"].rstrip("/"):
            report.error(
                "docs/hugo.yaml 的 baseURL 与 status.json 的 site.baseURL 不一致："
                f"{m.group(1).strip()} vs {site['baseURL']}"
            )

    sections = manifest.get("sections") or []
    posts = manifest.get("posts") or []

    if not sections and not posts:
        report.error("清单里既没有 sections 也没有 posts，没有任何内容会被发布")

    section_ids = set()
    for sec in sections:
        where = f"section {sec.get('id')!r}"
        for key in ("id", "slug", "title"):
            if not sec.get(key):
                report.error(f"{where} 缺少必填字段 {key}")
        sid = sec.get("id")
        if sid in section_ids:
            report.error(f"{where} 的 id 重复")
        section_ids.add(sid)
        if not SLUG_RE.match(str(sec.get("slug", ""))):
            report.error(f"{where} 的 slug 必须是小写 ASCII（kebab-case），当前 {sec.get('slug')!r}")
        if sec.get("pin") and pins and sec["pin"] not in pins:
            report.error(
                f"{where} 用了未定义配色的 pin={sec['pin']!r}；"
                f"可选值：{', '.join(sorted(pins))}"
            )
        check_date(sec.get("date"), where, report)

    for sec in sections:
        parent = sec.get("parent")
        if parent and parent not in section_ids:
            report.error(f"section {sec.get('id')!r} 的 parent={parent!r} 不存在")

    seen_paths = {}
    for post in posts:
        where = f"post {post.get('id') or post.get('slug')!r}"
        for key in ("source", "section", "slug", "title"):
            if not post.get(key):
                report.error(f"{where} 缺少必填字段 {key}")
        if post.get("section") not in section_ids:
            report.error(f"{where} 的 section={post.get('section')!r} 不存在")
        if not SLUG_RE.match(str(post.get("slug", ""))):
            report.error(f"{where} 的 slug 必须是小写 ASCII（kebab-case），当前 {post.get('slug')!r}")
        check_date(post.get("date"), where, report)
        src = post.get("source")
        if src and not (REPO / src).exists():
            report.error(f"{where} 的 source 不存在: {src}")
        if post.get("pin") and pins and post["pin"] not in pins:
            report.error(f"{where} 用了未定义配色的 pin={post['pin']!r}")

        out = "posts/{}/{}".format(section_path(manifest, post.get("section")), post.get("slug"))
        if out in seen_paths:
            report.error(f"{where} 与 {seen_paths[out]} 的输出路径冲突: {out}")
        seen_paths[out] = where


def check_date(value, where: str, report: Report) -> None:
    if not value:
        report.error(f"{where} 缺少 date（笔记没有 git 历史时无法从别处推断，必须显式给出）")
        return
    if not DATE_RE.match(str(value)):
        report.error(f"{where} 的 date 必须是 YYYY-MM-DD，当前 {value!r}")
        return
    # buildFuture=false 会让未来日期的页面直接从构建结果里消失，
    # 表现是首页有卡片但点进去 404，所以这里必须提前拦住。
    today = _dt.date.today()
    try:
        d = _dt.date.fromisoformat(str(value))
    except ValueError:
        report.error(f"{where} 的 date 不是合法日期: {value!r}")
        return
    if d > today:
        report.warn(f"{where} 的 date={value} 在未来（今天是 {today.isoformat()}），"
                    "该页面不会出现在构建结果里")


# --------------------------------------------------------------------------
# 路径推导
# --------------------------------------------------------------------------

def section_path(manifest: dict, section_id: str) -> str:
    """把一个 section 的 id 展开成 content/posts 下的相对路径，支持嵌套。"""
    by_id = {s.get("id"): s for s in manifest.get("sections") or []}
    parts = []
    seen = set()
    cur = section_id
    while cur:
        if cur in seen:
            break
        seen.add(cur)
        sec = by_id.get(cur)
        if not sec:
            break
        parts.append(sec.get("slug"))
        cur = sec.get("parent")
    return "/".join(reversed(parts))


# --------------------------------------------------------------------------
# 正文转换
# --------------------------------------------------------------------------

def split_fences(text: str):
    """把正文切成 (is_code, lines) 段。所有语法重写只作用于非代码段。

    这一步是整个转换器的地基：slime-training.md 的 python 代码块里有
    `if self.role == "critic":` 这种 == 比较运算符，如果先做高亮替换就会把
    代码改坏。
    """
    lines = text.split("\n")
    out = []
    buf = []
    i = 0
    total = len(lines)
    while i < total:
        m = FENCE_OPEN_RE.match(lines[i])
        if not m:
            buf.append(lines[i])
            i += 1
            continue
        if buf:
            out.append((False, buf))
            buf = []
        fence = m.group(1)
        char = fence[0]
        close_re = re.compile(r"^ {0,3}" + re.escape(char) + r"{%d,}[ \t]*$" % len(fence))
        block = [lines[i]]
        i += 1
        closed = False
        while i < total:
            block.append(lines[i])
            if close_re.match(lines[i]):
                i += 1
                closed = True
                break
            i += 1
        if not closed:
            out.append((True, block))
            return out, True
        out.append((True, block))
    if buf:
        out.append((False, buf))
    return out, False


def split_inline(text: str):
    """把非代码段的文本切成 (kind, text)，kind ∈ {plain, code, math}。

    被保护起来的片段（行内代码、行内公式、`$$…$$` 块）不会被任何重写碰到。
    """
    parts = []
    i = 0
    total = len(text)
    start = 0
    while i < total:
        if text[i] == "\\":
            i += 2
            continue
        # 块级公式，可以跨行，优先于行内 $...$
        if text.startswith("$$", i):
            end = text.find("$$", i + 2)
            if end != -1:
                parts.append(("plain", text[start:i]))
                parts.append(("math", text[i:end + 2]))
                i = end + 2
                start = i
                continue
            i += 2
            continue
        if text[i] == "`":
            j = i
            while j < total and text[j] == "`":
                j += 1
            ticks = text[i:j]
            end = text.find(ticks, j)
            if end != -1:
                parts.append(("plain", text[start:i]))
                parts.append(("code", text[i:end + len(ticks)]))
                i = end + len(ticks)
                start = i
                continue
            i = j
            continue
        if text[i] == "$":
            nl = text.find("\n", i)
            end = text.find("$", i + 1)
            if end != -1 and end > i + 1 and (nl == -1 or end < nl):
                parts.append(("plain", text[start:i]))
                parts.append(("math", text[i:end + 1]))
                i = end + 1
                start = i
                continue
            i += 1
            continue
        i += 1
    parts.append(("plain", text[start:]))
    return parts


class Doc:
    """一篇待转换的文档（文章或专题落地页）。"""

    def __init__(self, manifest, report: Report, source_rel: str, out_dir: Path,
                 link_map: dict, demote_h1: bool = True) -> None:
        self.manifest = manifest
        self.report = report
        self.source_rel = source_rel
        self.out_dir = out_dir
        self.link_map = link_map
        self.demote_h1 = demote_h1
        self.images: list[Path] = []
        self.label = source_rel

    # -- 图片 ---------------------------------------------------------------
    def _asset(self, name: str):
        root = REPO / (self.manifest.get("assetRoot") or "images")
        candidate = root / name
        if candidate.exists():
            return candidate
        # 兼容笔记里写了子目录路径的情况
        candidate = REPO / name
        if candidate.exists():
            return candidate
        return None

    def _rewrite_embed(self, match: re.Match) -> str:
        target, _, alias = match.group(1).partition("|")
        name = target.strip()
        alt = alias.strip()
        if alt.isdigit():
            alt = ""
        path = self._asset(name)
        if path is None:
            self.report.warn(f"图片缺失: {name}（来自 {self.source_rel}），已插入占位")
            return f'<span class="asset-missing">⚠️ 图片缺失：<code>{name}</code></span>'
        self.images.append(path)
        label = alt or name
        # 相对路径 + leaf page bundle：PaperMod 的 render-image.html 会通过
        # .PageInner.Resources 解析它，从而带上 /llm/ 前缀，站点换路径也不会裂。
        return f"![{label}]({path.name})"

    def _rewrite_link(self, match: re.Match) -> str:
        text, target, frag = match.group(1), match.group(2), match.group(3) or ""
        base = os.path.dirname(self.source_rel)
        normalized = os.path.normpath(os.path.join(base, target)).replace(os.sep, "/")
        dest = self.link_map.get(normalized)
        if dest is None:
            self.report.error(
                f"{self.source_rel} 里的内部链接指向未发布的笔记: {target}"
                "（要么把它加进 status.json，要么改成外部链接）"
            )
            return match.group(0)
        # 用 relref 而不是写死的 URL：Hugo 会自动补上 /llm/ 前缀，
        # 目标不存在时构建会直接报错，而不是产出一个 404 链接。
        return f'[{text}]({{{{< relref "{dest}" >}}}}{frag})'

    def _rewrite_plain(self, chunk: str) -> str:
        if "![" in chunk:
            chunk = EMBED_RE.sub(self._rewrite_embed, chunk)
        if "](" in chunk:
            chunk = MD_LINK_RE.sub(self._rewrite_link, chunk)
        if "[[" in chunk:
            def wikilink(m):
                self.report.warn(
                    f"{self.source_rel} 里有 Obsidian wikilink {m.group(0)}，"
                    "转换器不会猜测目标，已原样保留"
                )
                return m.group(0)
            chunk = WIKILINK_RE.sub(wikilink, chunk)
        if "==" in chunk:
            if chunk.count("==") % 2:
                self.report.note(f"{self.source_rel} 有一行 == 无法配对，已原样保留: {chunk.strip()[:60]}")
            chunk = HIGHLIGHT_RE.sub(lambda m: f"<mark>{m.group(1)}</mark>", chunk)
        return chunk

    def body(self, text: str) -> str:
        text = text.replace("\r\n", "\n").replace("\r", "\n")
        blocks, unclosed = split_fences(text)
        if unclosed:
            self.report.warn(f"{self.source_rel} 有未闭合的代码围栏，其后的内容都按代码处理")

        out = []
        for is_code, lines in blocks:
            if is_code:
                out.append("\n".join(lines))
                continue
            if self.demote_h1:
                # 笔记正文里的 H1 会和 PaperMod 的页面标题打架，降一级。
                lines = [H1_RE.sub("## ", ln) if H1_RE.match(ln) else ln for ln in lines]
            chunk = "\n".join(lines)
            out.append("".join(
                part if kind != "plain" else self._rewrite_plain(part)
                for kind, part in split_inline(chunk)
            ))
        body = "\n".join(out).strip("\n")
        return body + "\n" if body else ""


# --------------------------------------------------------------------------
# frontmatter
# --------------------------------------------------------------------------

def toml_value(value) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, str):
        # json 的转义是 TOML basic string 的子集（\uXXXX、\n、\" 都合法）
        return json.dumps(value, ensure_ascii=False)
    if isinstance(value, list):
        return "[" + ", ".join(json.dumps(v, ensure_ascii=False) for v in value) + "]"
    raise TypeError(f"无法写入 frontmatter 的类型: {type(value)!r}")


def frontmatter_toml(fields: dict) -> str:
    lines = ["+++"]
    for key, value in fields.items():
        if value is None:
            continue
        lines.append(f"{key} = {toml_value(value)}")
    lines.append("+++")
    return "\n".join(lines)


def header(source_rel: str) -> str:
    return f"{GEN_MARK} from {source_rel}; DO NOT EDIT -->"


# --------------------------------------------------------------------------
# 构建输出计划
# --------------------------------------------------------------------------

class Output:
    def __init__(self, path: Path, text: str, images=None) -> None:
        self.path = path
        self.text = text
        self.images = images or []


def build_plan(manifest: dict, report: Report):
    outputs = []
    link_map = {}

    # 先建链接映射，内部链接重写需要知道每个源文件最终落在哪
    for post in manifest.get("posts") or []:
        sec_path = section_path(manifest, post["section"])
        link_map[post["source"]] = f"posts/{sec_path}/{post['slug']}/index.md"
    for sec in manifest.get("sections") or []:
        if sec.get("index_source"):
            link_map[sec["index_source"]] = f"posts/{section_path(manifest, sec['id'])}/_index.md"

    # 专题落地页
    for sec in manifest.get("sections") or []:
        rel_dir = Path("posts") / section_path(manifest, sec["id"])
        out_dir = CONTENT / rel_dir
        src = sec.get("index_source")
        if src:
            doc = Doc(manifest, report, src, out_dir, link_map)
            body = doc.body((REPO / src).read_text(encoding="utf-8"))
            images = doc.images
        else:
            body = f"> {sec.get('description') or '本专题内容正在整理中。'}\n"
            images = []
        fields = {
            "title": sec.get("title"),
            "date": sec.get("date"),
            "description": sec.get("description"),
            "tags": sec.get("tags"),
            "weight": sec.get("weight"),
            "pin": sec.get("pin"),
            "toc": sec.get("toc"),
            "draft": sec.get("draft"),
        }
        text = frontmatter_toml(fields) + "\n\n" + header(src or f"section:{sec['id']}") + "\n\n" + body
        outputs.append(Output(out_dir / "_index.md", text, images))

    # 文章
    for post in manifest.get("posts") or []:
        src = post["source"]
        sec_path = section_path(manifest, post["section"])
        out_dir = CONTENT / "posts" / sec_path / post["slug"]
        doc = Doc(manifest, report, src, out_dir, link_map,
                  demote_h1=post.get("demoteH1", True))
        body = doc.body((REPO / src).read_text(encoding="utf-8"))
        if not body.strip():
            if post.get("stub"):
                body = "> 🚧 本章节正在撰写中，内容会随笔记更新同步发布。\n"
            else:
                report.warn(f"{src} 转换后是空文档，却仍被发布")
        elif post.get("stub"):
            report.note(f"{src} 标记了 stub 但已有内容，可以把 status.json 里的 stub 去掉")
        fields = {
            "title": post.get("title"),
            "date": post.get("date"),
            "description": post.get("description"),
            "tags": post.get("tags"),
            "weight": post.get("weight"),
            "pin": post.get("pin"),
            "toc": post.get("toc"),
            "draft": post.get("draft"),
        }
        text = frontmatter_toml(fields) + "\n\n" + header(src) + "\n\n" + body
        outputs.append(Output(out_dir / "index.md", text, doc.images))

    # 固定页面
    for page in manifest.get("pages") or []:
        kind = page.get("kind")
        if kind == "search":
            text = (
                "---\n"
                f"title: {json.dumps(page.get('title') or 'Search', ensure_ascii=False)}\n"
                'layout: "search"\n'
                f"placeholder: {json.dumps(page.get('description') or '搜索笔记…', ensure_ascii=False)}\n"
                "---\n"
            )
            outputs.append(Output(CONTENT / "search.md", text))
        elif kind == "home":
            text = frontmatter_toml({"title": page.get("title")}) + "\n\n"
            src = page.get("source")
            if src:
                doc = Doc(manifest, report, src, CONTENT, link_map)
                text += header(src) + "\n\n" + doc.body((REPO / src).read_text(encoding="utf-8"))
                outputs.append(Output(CONTENT / "_index.md", text, doc.images))
            else:
                outputs.append(Output(CONTENT / "_index.md", text))
        else:
            report.error(f"未知的 page kind: {kind!r}")

    return outputs


def audit_scan_roots(manifest: dict, report: Report) -> None:
    """列出仓库里存在、但没有被清单收录的笔记，提醒是「故意不发」还是「忘了」。"""
    published = {p["source"] for p in manifest.get("posts") or [] if p.get("source")}
    published |= {s["index_source"] for s in manifest.get("sections") or [] if s.get("index_source")}
    published |= {p["source"] for p in manifest.get("pages") or [] if p.get("source")}
    skipped = {s.get("source") for s in manifest.get("skipped") or []}

    for root in manifest.get("scanRoots") or []:
        root_dir = REPO / root
        if not root_dir.is_dir():
            continue
        for path in sorted(root_dir.rglob("*.md")):
            rel = path.relative_to(REPO).as_posix()
            if rel in published or rel in skipped:
                continue
            size = path.stat().st_size
            hint = "空文件" if size == 0 else f"{size} 字节"
            report.warn(
                f"未被 status.json 收录，不会发布: {rel}（{hint}）"
            )


# --------------------------------------------------------------------------
# 写盘
# --------------------------------------------------------------------------

def write_outputs(outputs, report: Report, dry_run: bool) -> int:
    expected = {o.path.resolve() for o in outputs}
    stale = []

    # 清掉上一轮生成、这一轮已不在清单里的文件（只删带生成标记的）
    if CONTENT.exists():
        for path in CONTENT.rglob("*.md"):
            if path.resolve() in expected:
                continue
            try:
                text = path.read_text(encoding="utf-8")
            except OSError:
                continue
            if text.lstrip().startswith(GEN_MARK) or GEN_MARK in text[:400]:
                stale.append(path)

    drift = []
    for out in outputs:
        if out.path.exists():
            try:
                if out.path.read_text(encoding="utf-8") != out.text:
                    drift.append(out.path)
            except OSError:
                drift.append(out.path)
        else:
            drift.append(out.path)

    if dry_run:
        if drift:
            report.note(
                f"docs/content 有 {len(drift)} 个文件与当前笔记不一致，"
                "本地跑一次 python3 tools/sync.py 即可同步"
            )
        if stale:
            report.note(f"有 {len(stale)} 个已废弃的生成文件待清理")
        return 0

    if stale:
        for path in stale:
            path.unlink()
        report.note(f"清理了 {len(stale)} 个已废弃的生成文件")

    copied = 0
    for out in outputs:
        out.path.parent.mkdir(parents=True, exist_ok=True)
        out.path.write_text(out.text, encoding="utf-8")
        for image in out.images:
            target = out.path.parent / image.name
            if not target.exists() or target.stat().st_mtime < image.stat().st_mtime:
                shutil.copy2(image, target)
                copied += 1
    report.note(f"写入了 {len(outputs)} 个文件，复制了 {copied} 张图片")
    return 0


def clean_content(report: Report) -> None:
    if CONTENT.exists():
        shutil.rmtree(CONTENT)
        report.note("已清空 docs/content")


# --------------------------------------------------------------------------
# 入口
# --------------------------------------------------------------------------

def main(argv=None) -> int:
    parser = argparse.ArgumentParser(
        description="把 Obsidian 笔记同步成 docs/ 下的 Hugo 站点内容",
    )
    parser.add_argument("--check", action="store_true", help="只校验并比对，不写文件")
    parser.add_argument("--strict", action="store_true", help="把警告也当作失败")
    parser.add_argument("--clean", action="store_true", help="先清空 docs/content 再生成")
    parser.add_argument("--serve", action="store_true", help="生成后启动 hugo server")
    args = parser.parse_args(argv)

    report = Report()
    manifest = load_manifest(report)
    if manifest:
        validate_manifest(manifest, report)

    outputs = []
    if manifest and not report.errors:
        outputs = build_plan(manifest, report)
        audit_scan_roots(manifest, report)

    if report.errors:
        print_report(report, outputs)
        print("\n同步失败：请先修掉上面的 error。", file=sys.stderr)
        return 1

    if args.clean and not args.check:
        clean_content(report)

    write_outputs(outputs, report, dry_run=args.check)

    print_report(report, outputs)
    if args.check:
        print("\n校验通过（未写入任何文件）。")
    if args.strict and report.warnings:
        print(f"\n--strict：有 {len(report.warnings)} 条警告，视为失败。", file=sys.stderr)
        return 1

    if args.serve:
        if shutil.which("hugo") is None:
            print("\n没有找到 hugo，无法预览。macOS 上可以 `brew install hugo` 安装。", file=sys.stderr)
            return 1
        return subprocess.call(["hugo", "serve", "--source", str(DOCS)])
    return 0


def print_report(report: Report, outputs) -> None:
    for msg in report.warnings:
        print(f"WARN  {msg}")
    for msg in report.errors:
        print(f"ERROR {msg}", file=sys.stderr)
    for msg in report.notes:
        print(f"      {msg}")
    if outputs:
        print(f"\n共 {len(outputs)} 个页面：")
        for out in outputs:
            print(f"  {out.path.relative_to(REPO)}")
    summary = f"\n{len(outputs)} 个页面 / {len(report.warnings)} 条警告 / {len(report.errors)} 个错误"
    print(summary)


if __name__ == "__main__":
    sys.exit(main())
